# This is a manual workflow to clean up my Azure Resource Group and save us all $$$!

name: Azure Cleanup

on: 
  ## Could also run on a schedule, but you need to remove the permissin check for the github.actor being the repo owner and specify the rg name
  #schedule:
  #  - cron: '0 0 * * *' #everyday at midnight
  workflow_dispatch:
    inputs:
      Azure_RG:
        description: 'Azure Resource Group'     
        required: true
jobs:
  permission:
    name: permission check
    runs-on: ubuntu-latest
    if: github.actor == github.event.repository.owner.login
    steps:
    - name: check permission
      run: echo permission pass
       
  teardown-azure-rg:
    name: Teardown Azure Resource Group
    needs: permission
    runs-on: ubuntu-latest
    steps:
    - uses: azure/login@v1.1
      with:
        creds: ${{ secrets.AZURE_CREDS }}
        
        ## Delete the Azure Resource Group with optional [--yes] parameter to NOT prompt for confirmation
    - run: |
        az group delete -n ${{ github.event.inputs.Azure_RG }} --yes

  
